#!/usr/bin/env bash
# Transfer the file using scp
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo ngix -t
sudo service nginx start
