#!/usr/bin/env bash
# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create a basic index.html file
echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null

# Add a redirection rule to Nginx configuration
sudo sed -i '/server_name _;/a \\trewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/my_404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \\terror_page 404 /my_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
