#!/usr/bin/env bash
# 0. Double the number of webservers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/my_404.html > /dev/null
sudo sed -i "52i error_page 404 /my_404.html;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
