#!/usr/bin/env bash
# Transfer the file using scp
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp $SCP_OPTIONS -i "$ssh_key" "$file_path" "$username@$server_ip":~/
