#!/usr/bin/env bash
# 1. Install your load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
sudo echo '
frontend aezzahir42.aezzahir.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 431011-web-01 18.234.253.112:80
        server 431011-web-02 54.196.41.205:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart