#!/usr/bin/env bash
# 1. Install your load balancer
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  aezzahir_frontend
        bind *:80
        mode http
        default_backend aezzahir_backend
backend aezzahir_backend
        balance roundrobin
        server 431011-web-01 18.234.253.112:80 check
        server 431011-web-02 54.196.41.205:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart