#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times. Using While loop
i="1"
while [ "$i" -le 10 ]; do
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
