#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#   display hours from 0 to 12
#   display minutes from 1 to 59

h=0
while [ "$h" -lt 12 ]; do
    echo "Hour: $h"
    mn=1
    while [ "$mn" -lt 60 ]; do
        echo "$mn"
        mn=$((mn+1))
    done
    h=$((h+1))
done
