#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.

cp -f /etc/hosts /etc/hosts.new

echo "127.0.0.2 localhost" > /etc/hosts.new
echo "8.8.8.8 facebook.com" >> /etc/hosts.new

cp -f /etc/hosts.new /etc/hosts
