#!/usr/bin/env bash
# Hi nginx must be running as nginx user
sed -i 's/user\s*nginx;/user nginx nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /var/www/html
service nginx restart
